variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: parity/rust-builder:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
  - target/
  - $CARGO_HOME

stages:
  - build
  - test

check-format:
  stage: build
  artifacts:
    paths:
      - target/debug/
    when: always
    expire_in: 1 week
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

check:
  stage: build
  artifacts:
    paths:
      - target/debug/
    when: always
    expire_in: 1 week
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - WASM_BUILD_TYPE=release cargo check --locked

test:
  stage: test
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - cargo test --all
